apiVersion: v1
kind: ConfigMap
metadata:
  name: common-att-eservices-data
  namespace: att-eservices
data:
  DB_HOST: "interop-platform-data-att.cluster-c5mm6mwy4v3q.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "att_eservices"
  DB_USE_SSL: "true"
  DB_SCHEMA: "att"
